import { test, expect } from '@playwright/test';

// Explicit opt-in: this writes test catalog records and a COD order to STAGING.
test('staging admin creates catalog, customer orders a bundle, owner verifies and cancels',async({page},info)=>{
 test.skip(process.env.RUN_ADMIN_LIVE!=='1'||!process.env.TEST_ADMIN_EMAIL||!process.env.TEST_ADMIN_PASSWORD,'Requires a configured staging Supabase project and admin test credentials.');
 test.skip(info.project.name!=='desktop','Run once to avoid duplicate staging orders.');
 test.setTimeout(180000);
 const token=Date.now().toString(),top=`Test Top ${token}`,bottom=`Test Bottom ${token}`,outfit=`Test Outfit ${token}`;
 await page.goto('/admin');await expect(page).toHaveURL(/\/admin\/login/);
 await page.getByLabel('EMAIL ADDRESS').fill(process.env.TEST_ADMIN_EMAIL!);await page.getByLabel('PASSWORD',{exact:true}).fill(process.env.TEST_ADMIN_PASSWORD!);await page.getByRole('button',{name:'SECURE SIGN IN'}).click();
 await expect(page.getByRole('navigation',{name:'Admin navigation'})).toBeVisible();
 for(const [name,category,size,price] of [[top,'Tops','XL','2000'],[bottom,'Bottoms','M-L','3000']]){
  await page.goto('/admin?tab=products');await page.getByRole('button',{name:'ADD PRODUCT',exact:true}).click();
  const editor=page.locator('.product-editor');await editor.getByLabel('PRODUCT NAME',{exact:true}).fill(name);await editor.getByLabel('CATEGORY',{exact:true}).selectOption(category);await editor.getByLabel('PRICE (DZD)',{exact:true}).fill(price);await editor.getByLabel('DESCRIPTION',{exact:true}).fill('Staging verification item. Not for sale.');
  await editor.locator('.admin-images').first().getByLabel('IMAGE URLS (one per line)').fill('/products/sakura-shirt/01-cover.jpeg\n/products/sakura-shirt/02-rear.jpeg');
  await editor.getByLabel('Variant size').fill(size);await editor.getByLabel('Variant stock').fill('8');await editor.getByLabel('VISIBILITY').selectOption('true');await editor.getByRole('button',{name:'SAVE PIECE'}).click();await expect(editor).toHaveCount(0);
 }
 await page.reload();await expect(page.locator('.admin-product').filter({hasText:top})).toHaveCount(1);
 await page.locator('.admin-product').filter({hasText:top}).getByRole('button',{name:'Edit',exact:true}).click();await page.locator('.product-editor').getByLabel('PRICE (DZD)',{exact:true}).fill('2100');await page.getByRole('button',{name:'SAVE PIECE'}).click();await expect(page.locator('.product-editor')).toHaveCount(0);
 await page.goto('/admin?tab=outfits');await page.getByRole('button',{name:'ADD OUTFIT'}).click();let editor=page.locator('.product-editor');await editor.getByLabel('OUTFIT NAME').fill(outfit);await editor.getByLabel('TOP PRODUCT').selectOption({label:top});await editor.getByLabel('BOTTOM PRODUCT').selectOption({label:bottom});await editor.getByLabel('NORMAL COMBINED PRICE (DZD)').fill('5100');await editor.getByLabel('SELLING PRICE (DZD)').fill('4500');await editor.getByLabel('DESCRIPTION',{exact:true}).fill('Staging verification outfit with independent sizes.');await editor.getByLabel('IMAGE URLS (one per line)').fill('/outfits/sakura-summer/01-cover.jpeg\n/outfits/bootcut-slim-combo/01-cover.jpeg');await editor.getByLabel('VISIBILITY').selectOption('true');await editor.getByRole('button',{name:'SAVE OUTFIT'}).click();await expect(editor).toHaveCount(0);
 await page.reload();await page.locator('.admin-product').filter({hasText:outfit}).getByRole('button',{name:'Edit',exact:true}).click();editor=page.locator('.product-editor');await editor.getByLabel('SELLING PRICE (DZD)').fill('4400');await editor.getByRole('button',{name:'SAVE OUTFIT'}).click();await expect(editor).toHaveCount(0);
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
 await page.goto(`/product/test-top-${token}`);await expect(page.locator('.detail-price:visible')).toContainText('2,100');await page.getByRole('button',{name:'XL',exact:true}).click();await page.getByRole('button',{name:'ADD TO BAG',exact:true}).click();
 await page.goto('/shop?category=Outfits');await page.locator('.outfit-card').filter({hasText:outfit}).getByRole('link',{name:outfit,exact:true}).click();
 await expect(page.locator('.gallery-thumbs button')).toHaveCount(2);await page.getByRole('button',{name:'Show image 2',exact:true}).click();await expect(page.locator('.gallery-main img:visible')).toHaveAttribute('src','/outfits/bootcut-slim-combo/01-cover.jpeg');
 await page.getByRole('group',{name:top,exact:true}).getByRole('button',{name:'XL',exact:true}).click();await expect(page.getByRole('button',{name:'ADD TO BAG',exact:true})).toBeDisabled();await page.getByRole('group',{name:bottom,exact:true}).getByRole('button',{name:'M-L',exact:true}).click();await page.getByRole('button',{name:'ADD TO BAG',exact:true}).click();
 await page.goto('/cart');await page.reload();await expect(page.locator('.cart-item')).toHaveCount(2);await page.goto('/checkout');await page.locator('[name=name]').fill(`Staging Test ${token}`);await page.locator('[name=phone]').fill('0555000000');await page.locator('[name=wilaya]').selectOption('16 Alger');await page.locator('[name=commune]').fill('Hydra');await page.locator('[name=address]').fill('Staging verification only - do not ship');await page.getByRole('button',{name:'PLACE MY ORDER'}).click();await expect(page).toHaveURL(/order-confirmation/);const reference=new URL(page.url()).searchParams.get('ref')!;
 await page.goto('/admin?tab=orders');const order=page.locator('.admin-order').filter({hasText:reference});await order.locator('summary').click();await expect(order).toContainText('7,100 DZD');await expect(order).toContainText(top);await expect(order).toContainText('M-L');await expect(order).toContainText('XL');await order.locator('select').selectOption('confirmed');await expect(page.getByRole('status')).toContainText('updated');await page.reload();await expect(order.locator('select')).toHaveValue('confirmed');
 // Leave the audit trail, cancel the test order and remove only our catalog fixtures.
 await order.locator('select').selectOption('cancelled');await expect(page.getByRole('status')).toContainText('updated');
 for(const [tab,names] of [['outfits',[outfit]],['products',[top,bottom]]] as const){await page.goto(`/admin?tab=${tab}`);for(const name of names){const row=page.locator('.admin-product').filter({hasText:name});await row.getByRole('button',{name:'Delete',exact:true}).click();await row.getByRole('button',{name:'Confirm delete',exact:true}).click();await expect(row).toHaveCount(0);}}
});
