import { DeliveryInformation } from '@/components/product-delivery';
import { getTranslator } from '@/lib/i18n/server';
export const metadata = {
  title: 'Contact & care'
};
export default async function Contact() {
  const t = await getTranslator();
  return <section className="page-shell"><div className="page-intro"><span className="eyebrow">{t("A LITTLE HUMAN CONNECTION.")}</span><h1>{t("We’re here for you.")}</h1><p>{t("Your questions deserve a considered answer.")}</p></div><div className="contact-layout"><div><div className="contact-block"><h2>{t("Let’s talk.")}</h2><p>{t("Explore product details and individual size guides to find the right piece.")}</p></div><div className="contact-block"><h2>{t("Already placed an order?")}</h2><p>{t("Keep your order reference for any questions about your selection.")}</p></div><div className="contact-block"><span className="eyebrow">{t("CELESTIALS / ALGERIA")}</span><p style={{
            marginTop: 18
          }}>{t("Independent spirit.")}<br />{t("A higher standard of everyday.")}</p></div></div><div><div className="contact-block" id="delivery"><h2>{t("The useful details.")}</h2><details open><summary>{t("Delivery across Algeria")}</summary><DeliveryInformation /></details><details><summary>{t("How does cash on delivery work?")}</summary><p>{t("Cash on delivery means payment is collected when a parcel is delivered. This concept illustrates that checkout option.")}</p></details><details><summary>{t("Changes, returns & exchanges")}</summary><p>{t("For an actual purchase, confirm change, return and exchange conditions directly with the brand. This concept does not establish an official policy.")}</p></details><details><summary>{t("How is my information used?")}</summary><p>{t("The checkout collects a name, phone number and delivery address. Order records are restricted to authorized administrators. For this presentation, use demonstration details rather than personal information.")}</p></details></div><div className="contact-block" id="sizing"><h2>{t("Find your fit.")}</h2><p>{t("Sizing varies by product. Check the Size Guide on the individual product page for the exact measurements and the available size options.")}</p><p>{t("Tops and bottoms use different measurements, and size labels can vary between pieces. For outfits, check the separate Size Guide for each component. Use the supplied product chart; do not treat garment measurements as body measurements.")}</p></div></div></div></section>;
}
