import { DeliveryInformation } from '@/components/product-delivery';
import { getTranslator } from '@/lib/i18n/server';
export const metadata = {
  title: 'Contact & care'
};
export default async function Contact() {
  const t = await getTranslator();
  return <section className="page-shell"><div className="page-intro"><span className="eyebrow">{t("A LITTLE HUMAN CONNECTION.")}</span><h1>{t("We’re here for you.")}</h1><p>{t("Your questions deserve a considered answer.")}</p></div><div className="contact-layout"><div><div className="contact-block"><h2>{t("Let’s talk.")}</h2><p>{t("Questions about a piece, the fit, or an existing order? Our customer service contact details will be available when the store opens.")}</p><div className="alert">{t("Getting ready for launch. Customer support contact information is being finalized.")}</div></div><div className="contact-block"><h2>{t("Already placed an order?")}</h2><p>{t("Keep your order reference handy. Our team will call the phone number you provided to confirm your selection and delivery details before dispatch.")}</p></div><div className="contact-block"><span className="eyebrow">{t("CELESTIALS / ALGERIA")}</span><p style={{
            marginTop: 18
          }}>{t("Independent spirit.")}<br />{t("A higher standard of everyday.")}</p></div></div><div><div className="contact-block" id="delivery"><h2>{t("The useful details.")}</h2><details open><summary>{t("Delivery across Algeria")}</summary><DeliveryInformation /></details><details><summary>{t("How does cash on delivery work?")}</summary><p>{t("Place your order without entering any payment details. Our team confirms your order by phone, then you pay the total shown at checkout in cash to the courier when your parcel arrives.")}</p></details><details><summary>{t("Changes, returns & exchanges")}</summary><p>{t("Tell our team about any changes when we call to confirm your order. Our full return and exchange policy will be published before orders open.")}</p></details><details><summary>{t("How is my information used?")}</summary><p>{t("Your name, phone number, and address are used to confirm and deliver your order. Order records are accessible only to authorized store administrators. Contact the store team for help with your information once support opens.")}</p></details></div><div className="contact-block" id="sizing"><h2>{t("Find your fit.")}</h2><p>{t("Sizing varies by product. Check the Size Guide on the individual product page for the exact measurements and the available size options.")}</p><p>{t("Tops and bottoms use different measurements, and size labels can vary between pieces. For outfits, check the separate Size Guide for each component. Use the supplied product chart; do not treat garment measurements as body measurements.")}</p></div></div></div></section>;
}
