import { getTranslator } from '@/lib/i18n/server';
import Image from 'next/image';
import { BrandMark } from '@/components/brand-mark';
import { HomeCategories } from '@/components/home-categories';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Package, ShieldCheck, Truck } from 'lucide-react';
export const dynamic = 'force-dynamic';
export default async function Home() {
  const t = await getTranslator();
  return <div className="home-page"><section className="hero celestials-hero"><div className="hero-artwork"><Image className="hero-image" src="/celestials/hero.jpg" alt={t("CELESTIALS campaign: a person above the city beneath the celis artwork and an airplane")} fill preload sizes="100vw" /></div><div className="hero-shade" /><div className="hero-top"><span>{t("INDEPENDENT SPIRIT. EVERYDAY UNIFORM.")}</span><span>{t("COLLECTION 001 — EST. 2026")}</span></div><div className="hero-content"><div className="eyebrow hero-eyebrow"><BrandMark className="hero-mark" />{t(" THE NEW EVERYDAY")}</div><h1>{t("ABOVE THE")}<br /><span>{t("ORDINARY.")}</span></h1><p>{t("Considered essentials for a world in motion.")}<br />{t("Made to wear your own way.")}</p><Link href="/shop" className="button button-light">{t("EXPLORE THE COLLECTION ")}<ArrowUpRight size={19} /></Link></div><div className="hero-bottom"><span>{t("LESS NOISE. MORE PRESENCE.")}</span><span>{t("SCROLL TO DISCOVER ")}<span className="down-arrow">↓</span></span></div><div className="hero-side">{t("CELESTIALS® / DAILY EXPRESSION")}</div></section><div className="manifesto-strip"><span>{t("DESIGNED WITH INTENTION")}</span><BrandMark className="strip-mark" /><span>{t("WORN WITHOUT RULES")}</span><BrandMark className="strip-mark" /><span>{t("ABOVE THE ORDINARY")}</span><BrandMark className="strip-mark" /><span>{t("CELESTIALS EVERYDAY")}</span><BrandMark className="strip-mark" /></div><HomeCategories /><section className="brand-section"><span className="brand-symbol"><BrandMark /></span><span className="eyebrow">{t("NOT JUST WHAT YOU WEAR. HOW YOU MOVE.")}</span><h2>{t("Quiet confidence.")}<br /><span>{t("Unmistakably you.")}</span></h2><p>{t("We believe the best pieces don’t ask for attention.")}<br />{t("They earn a place in your everyday. This is CELESTIALS.")}</p><Link href="/about" className="text-link">{t("THE STORY BEHIND THE LABEL ")}<ArrowRight size={17} /></Link></section><div className="service-strip"><div><Truck size={24} strokeWidth={1.2} /><span>{t("DELIVERED TO YOUR DOOR")}<small>{t("Across Algeria")}</small></span></div><div><ShieldCheck size={24} strokeWidth={1.2} /><span>{t("PAY WHEN IT ARRIVES")}<small>{t("Cash on delivery")}</small></span></div><div><Package size={24} strokeWidth={1.2} /><span>{t("CONSIDERED IN EVERY DETAIL")}<small>{t("From the first look to the last stitch")}</small></span></div></div></div>;
}
