 'use client';
import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { type Product, money } from '@/lib/types';
import type { OutfitDefinition } from '@/lib/outfits';
import { logout,updateOrder,deleteProduct,deleteOutfit } from '@/app/admin/actions';
import { ProductEditor } from './admin-product-editor';
import { AdminOutfitEditor } from './admin-outfit-editor';
type Order = {id:string;reference:string;customer_name:string;phone:string;wilaya:string;commune:string;address:string;notes:string;status:string;subtotal:number;shipping:number;total:number;created_at:string;order_items:{id:string;product_name:string;size:string;color:string;quantity:number;unit_price:number;order_item_components:{product_name:string;size:string;color:string}[]}[]};
const transitions:Record<string,string[]>={pending:['pending','confirmed','cancelled'],confirmed:['confirmed','shipped','cancelled'],shipped:['shipped','delivered'],delivered:['delivered'],cancelled:['cancelled']};
const label=(s:string)=>s==='pending'?'New':s.charAt(0).toUpperCase()+s.slice(1);
export function AdminDashboard({orders,products,outfits,orderCount,page}:{orders:Order[];products:Product[];outfits:OutfitDefinition[];orderCount:number;page:number}) {
 const router=useRouter(),params=useSearchParams();const tab=params.get('tab')||'dashboard';
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState<Product|null>(null),[outfitEditor,setOutfitEditor]=useState<OutfitDefinition|null>(null),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[deleting,setDeleting]=useState('');
 async function change(id:string,value:string){setBusy(true);setError('');try{const r=await updateOrder(id,value);if(r.error)setError(r.error);else{setNotice('Order status updated.');router.refresh();}}catch{setError('Unable to update. Please try again.');}finally{setBusy(false);}}
 async function remove(id:string,outfit=false){setBusy(true);setError('');try{const r=await (outfit?deleteOutfit:deleteProduct)(id);if(r.error)setError(r.error);else{setNotice('Deleted.');setDeleting('');router.refresh();}}catch{setError('Unable to delete. Please try again.');}finally{setBusy(false);}}
 function newProduct(){const id=crypto.randomUUID();setEditor({id,slug:'',name:'',category:'Tops',price:0,description:'',images:[],badge:null,active:false,product_variants:[{id:crypto.randomUUID(),product_id:id,size:'',color:'Black',color_hex:'#222222',stock:0}]});}
 function newOutfit(){setOutfitEditor({id:crypto.randomUUID(),slug:'',name:'',description:'',price:0,original_price:0,image:'',images:[],badge:null,active:false,components:[]});}
 function saved(){setEditor(null);setOutfitEditor(null);setNotice('Saved. Storefront data updated.');router.refresh();}
 const visible=orders.filter(o=>(!status||o.status===status)&&`${o.reference} ${o.customer_name} ${o.phone}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="page-shell admin-management"><div className="admin-heading"><div className="page-intro"><span className="eyebrow">CELESTIALS / BEHIND THE LABEL</span><h1>The studio.</h1></div><form action={logout}><button className="button button-outline">SIGN OUT</button></form></div>
 <nav className="admin-tabs" aria-label="Admin navigation">{['dashboard','products','outfits','orders'].map(t=><Link key={t} href={`/admin?tab=${t}`} aria-current={tab===t?'page':undefined} className={tab===t?'selected':''}>{label(t)}</Link>)}</nav>
 {error&&<p role="alert" className="alert error">{error}</p>}{notice&&<p role="status" className="alert">{notice}</p>}
 {tab==='dashboard'&&<><div className="admin-stats"><div><span>TOTAL PRODUCTS</span><strong>{products.length}</strong></div><div><span>TOTAL OUTFITS</span><strong>{outfits.length}</strong></div><div><span>TOTAL ORDERS</span><strong>{orderCount}</strong></div></div><h2>Recent orders</h2>{orders.slice(0,5).map(o=><div className="admin-product" key={o.id}><div><h3>{o.reference} / {o.customer_name}</h3><p>{money(o.total)} / {label(o.status)}</p></div><Link href={`/admin?tab=orders#order-${o.id}`}>View order</Link></div>)}{!orders.length&&<p>No orders yet.</p>}</>}
 {tab==='products'&&<><button className="button button-dark" onClick={newProduct}>ADD PRODUCT</button>{editor&&<ProductEditor key={editor.id} product={editor} close={()=>setEditor(null)} saved={saved}/>}<p className="summary-note">Unpublish to hide a piece. Products referenced by outfits or open orders are protected from deletion.</p>{products.map(p=><div className="admin-product" key={p.id}><img src={p.images[0]} alt={p.name}/><div><h3>{p.name}</h3><p>{money(p.price)} / {p.category} / {p.product_variants.reduce((n,v)=>n+v.stock,0)} in stock / {p.active?'Published':'Unpublished'}</p></div><button onClick={()=>setEditor(p)}>Edit</button>{deleting===p.id?<><button disabled={busy} onClick={()=>remove(p.id)}>Confirm delete</button><button onClick={()=>setDeleting('')}>Cancel</button></>:<button onClick={()=>setDeleting(p.id)}>Delete</button>}</div>)}</>}
 {tab==='outfits'&&<><button className="button button-dark" onClick={newOutfit}>ADD OUTFIT</button>{outfitEditor&&<AdminOutfitEditor key={outfitEditor.id} outfit={outfitEditor} products={products} close={()=>setOutfitEditor(null)} saved={saved}/>}<p className="summary-note">Outfits share their component products' sizes, guides and inventory. Unpublishing a component also hides its outfits.</p>{outfits.map(o=><div className="admin-product" key={o.id}><img src={o.images?.[0]||o.image} alt={o.name}/><div><h3>{o.name}</h3><p>{money(o.price)} / {o.active?'Published':'Unpublished'}</p></div><button onClick={()=>setOutfitEditor(o)}>Edit</button>{deleting===o.id?<><button disabled={busy} onClick={()=>remove(o.id,true)}>Confirm delete</button><button onClick={()=>setDeleting('')}>Cancel</button></>:<button onClick={()=>setDeleting(o.id)}>Delete</button>}</div>)}</>}
 {tab==='orders'&&<><div className="shop-tools"><label className="search-field"><input aria-label="Search orders on this page" placeholder="Search this page: order, name, phone" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter order status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{Object.keys(transitions).map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div><p className="summary-note">Page {page} of {Math.max(1,Math.ceil(orderCount/50))}. Search and status filters apply to this page. Cancel new or confirmed orders to restore stock; shipped orders can move to delivered.</p>
 {visible.map(o=><article className="admin-order" id={`order-${o.id}`} key={o.id}><div className="admin-order-head"><div><h3>{o.reference} / {money(o.total)}</h3><p>{new Date(o.created_at).toLocaleString('en-GB',{timeZone:'Africa/Algiers'})}</p></div><select aria-label={`Status for ${o.reference}`} disabled={busy} value={o.status} onChange={e=>change(o.id,e.target.value)}>{transitions[o.status].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div><details><summary>Order details / {o.customer_name}</summary><div className="admin-order-info"><div><strong>{o.customer_name}</strong><br/><a href={`tel:${o.phone}`}>{o.phone}</a><br/>{o.address}<br/>{o.commune}, {o.wilaya}{o.notes&&<p>Note: {o.notes}</p>}<p>Order ID: {o.id}<br/>Payment: Cash on delivery</p></div><div>{o.order_items.map(i=><div key={i.id}><p>{i.quantity} x {i.product_name} / {money(i.unit_price)} each</p>{i.order_item_components?.length?i.order_item_components.map((c,index)=><p key={index}>{c.product_name}: {c.size} / {c.color}</p>):<p>Size: {i.size} / {i.color}</p>}</div>)}<p>Subtotal: {money(o.subtotal)}<br/>Delivery: {money(o.shipping)}<br/><strong>Total: {money(o.total)}</strong></p></div></div></details></article>)}{!visible.length&&<div className="empty-state"><h2>No orders here yet.</h2></div>}<nav className="editor-actions" aria-label="Order pages">{page>1&&<Link className="button button-outline" href={`/admin?tab=orders&page=${page-1}`}>PREVIOUS</Link>}{page*50<orderCount&&<Link className="button button-outline" href={`/admin?tab=orders&page=${page+1}`}>NEXT</Link>}</nav></>}
 </section>;
}
