import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { seedProducts } from '../src/lib/catalog';
import { seedOutfits } from '../src/lib/outfits';

// Reuse the exact legacy guide metadata already migrated by the admin migration.
const migration = readFileSync('supabase/migrations/003_admin_management.sql','utf8');
function legacyGuide(slug:string) {
 const line=migration.split('\n').find(line=>line.startsWith('update public.products set size_guide=')&&line.includes(`'${slug}'`));
 if(!line)return null;
 const match=line.match(/jsonb_build_object\('image','([^']+)','alt','([^']+)'\)/);
 if(!match)throw new Error(`Cannot read existing size guide for ${slug}`);
 return {image:match[1],alt:match[2]};
}
const products=seedProducts.map(p=>({...p,original_price:p.original_price??null,size_guide:p.size_guide??legacyGuide(p.slug)}));
const outfits=seedOutfits.map(o=>({...o,images:o.images?.length?o.images:[o.image],badge:o.badge??null}));
const assets=[...products.flatMap(p=>[...p.images,...(p.size_guide?[p.size_guide.image]:[])]),...outfits.flatMap(o=>[...o.images,...o.components.flatMap(c=>[...(c.thumbnail?[c.thumbnail]:[]),...(c.size_guide?[c.size_guide.image]:[])])])];
for(const path of assets)if(path.startsWith('/')&&!existsSync(`public${path}`))throw new Error(`Missing original asset: ${path}`);
const json=(value:unknown)=>`'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
const sql=`-- Generated by scripts/generate-catalog-restore.ts from the existing CELESTIALS catalog.
-- Run in Supabase SQL Editor AFTER migrations 001, 002 and 003.
-- Choose "Run without RLS" if prompted. Existing table RLS is not changed.
-- No helper tables are created; the ID map exists only inside the DO block.
-- Additive: no existing records are deleted or updated. Safe to run again.
-- Missing variants retain original DEMO stock (12); existing stock is untouched.
begin;
-- Serialize with catalog administration and prevent concurrent variant insertion.
select pg_advisory_xact_lock(704031);
lock table public.products, public.product_variants, public.outfits in share row exclusive mode;
do $restore$
declare p jsonb; v jsonb; o jsonb; actual_id uuid; existing_slug text; components jsonb; product_id_map jsonb := '{}'::jsonb;
begin
 for p in select value from jsonb_array_elements(${json(products)}) loop
  select slug into existing_slug from public.products where id=(p->>'id')::uuid;
  if found and existing_slug<>p->>'slug' then raise exception 'Original product ID is already used by another slug: %',p->>'slug'; end if;
  if exists(select 1 from public.outfits where slug=p->>'slug') then raise exception 'Product slug is already used by an outfit: %',p->>'slug'; end if;
  select id into actual_id from public.products where slug=p->>'slug';
  if not found then
   actual_id:=(p->>'id')::uuid;
   insert into public.products(id,slug,name,category,price,original_price,description,images,badge,active,size_guide)
   values(actual_id,p->>'slug',p->>'name',p->>'category',(p->>'price')::integer,(p->>'original_price')::integer,p->>'description',array(select jsonb_array_elements_text(p->'images')),p->>'badge',(p->>'active')::boolean,nullif(p->'size_guide','null'::jsonb));
  end if;
  product_id_map := product_id_map || jsonb_build_object(p->>'id',actual_id);
  for v in select value from jsonb_array_elements(p->'product_variants') loop
   if exists(select 1 from public.product_variants where id=(v->>'id')::uuid and product_id<>actual_id) then raise exception 'Original variant ID is already used by another product: %',v->>'id'; end if;
   -- Retain admin edits, sold stock and existing variant IDs; add only missing options.
   if not exists(select 1 from public.product_variants where id=(v->>'id')::uuid or (product_id=actual_id and lower(size)=lower(v->>'size') and lower(color)=lower(v->>'color'))) then
    insert into public.product_variants(id,product_id,size,color,color_hex,stock) values((v->>'id')::uuid,actual_id,v->>'size',v->>'color',v->>'color_hex',(v->>'stock')::integer);
   end if;
  end loop;
 end loop;
 for o in select value from jsonb_array_elements(${json(outfits)}) loop
  select slug into existing_slug from public.outfits where id=(o->>'id')::uuid;
  if found and existing_slug<>o->>'slug' then raise exception 'Original outfit ID is already used by another slug: %',o->>'slug'; end if;
  if exists(select 1 from public.products where slug=o->>'slug') then raise exception 'Outfit slug is already used by a product: %',o->>'slug'; end if;
  if not exists(select 1 from public.outfits where slug=o->>'slug') then
   -- Reuse products already created with the same slug, even with different UUIDs.
   select jsonb_agg(c.value || jsonb_build_object('product_id',product_id_map->>(c.value->>'product_id')) order by c.ordinality) into components
   from jsonb_array_elements(o->'components') with ordinality c(value,ordinality);
   insert into public.outfits(id,slug,name,price,original_price,image,images,description,active,badge,components)
   values((o->>'id')::uuid,o->>'slug',o->>'name',(o->>'price')::integer,(o->>'original_price')::integer,o->'images'->>0,array(select jsonb_array_elements_text(o->'images')),o->>'description',(o->>'active')::boolean,o->>'badge',components);
  end if;
 end loop;
end;
$restore$;
commit;
-- Inspect the database-backed catalog, including products created by the owner.
select p.slug,p.name,p.category,p.price,p.active,count(v.id) as variants,coalesce(sum(v.stock),0) as stock
from public.products p left join public.product_variants v on v.product_id=p.id
group by p.id order by p.category,p.name;
select slug,name,price,original_price,active,components from public.outfits order by name;
`;
writeFileSync('supabase/restore-original-catalog.sql',sql,'utf8');
console.log(`Generated additive restore: ${products.length} products, ${products.reduce((n,p)=>n+p.product_variants.length,0)} variants, ${outfits.length} outfits; all referenced assets exist.`);
